#!/usr/bin/env bash

# Launch simulator
me=`basename "$0"`
echo `pwd`
sim="/media/lyn/Samsung_T5/DroneSim/DroneSim_Lin.x86_64" #${1:-DroneSim}  # default path to executable
if [[ -x ${sim} ]]
then
	echo "[$me] Starting simulator: $sim"
	$sim
else
	echo "[$me] Simulator not found/not an executable: $sim" >&2
	echo "[$me] Start manually or specify on command line: sim:=<full path to executable>" >&2
fi
