from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.policy_gradients import DDPG
from quad_controller_rl.agents.policy_gradients_non_takeoff import DDPG2
from quad_controller_rl.agents.pg3 import DDPG3